name: (PRD) Deploy to Firebase on PR
'on': 
  pull_request:
    branches:
      - main
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARE_BY_CODE }}'
          projectId: care-by-code
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
