name: (DEV) Deploy to Firebase on merge
'on':
  push:
    branches:
      - development
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARE_BY_CODE_DEVELOPMENT }}'
          channelId: live
          projectId: care-by-code-development
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
